import type { CardDefinition } from "../types/cards";

export const debugOnlyCards: CardDefinition[] = [
  {
    id: "debug_control_own_set_boost",
    name: "Debug 前借り",
    card_type: "control",
    rarity: "rare",
    attack: 0,
    block: 0,
    speed: 0,
    tags: ["debug", "set", "attack"],
    effect_text: "自分の公開しているバトルカードを1枚選ぶ。そのカードの攻撃+2。",
    enabled: true,
    play_zone: "instant",
    after_play_zone: "discard",
    slot_type: "",
    flavor_text: "",
    effects: [
      {
        id: "debug_control_own_set_boost_01",
        seq: 1,
        enabled: true,
        trigger: "on_play",
        priority: 100,
        effect_type: "custom",
        keyword: "debug_boost_own_revealed_set_attack",
        display_text: "自分の公開しているバトルカードを1枚選ぶ。そのカードの攻撃+2。",
      },
    ],
    notes: "Debug only.",
  },
  {
    id: "debug_control_opponent_revealed_weaken",
    name: "Debug 露見崩し",
    card_type: "control",
    rarity: "rare",
    attack: 0,
    block: 0,
    speed: 0,
    tags: ["debug", "set", "debuff"],
    effect_text: "公開済みの相手のバトルカードを1枚選ぶ。そのカードの攻撃-1。",
    enabled: true,
    play_zone: "instant",
    after_play_zone: "discard",
    slot_type: "",
    flavor_text: "",
    effects: [
      {
        id: "debug_control_opponent_revealed_weaken_01",
        seq: 1,
        enabled: true,
        trigger: "on_play",
        priority: 100,
        effect_type: "custom",
        keyword: "debug_weaken_revealed_opponent_attack",
        display_text: "公開済みの相手のバトルカードを1枚選ぶ。そのカードの攻撃-1。",
      },
    ],
    notes: "Debug only.",
  },
  {
    id: "debug_control_reorder_top3",
    name: "Debug 先読み",
    card_type: "control",
    rarity: "rare",
    attack: 0,
    block: 0,
    speed: 0,
    tags: ["debug", "deck"],
    effect_text: "自分の山札の上から3枚を見て、好きな順で戻す。",
    enabled: true,
    play_zone: "instant",
    after_play_zone: "discard",
    slot_type: "",
    flavor_text: "",
    effects: [
      {
        id: "debug_control_reorder_top3_01",
        seq: 1,
        enabled: true,
        trigger: "on_play",
        priority: 100,
        effect_type: "custom",
        keyword: "debug_reorder_top3",
        display_text: "自分の山札の上から3枚を見て、好きな順で戻す。",
      },
    ],
    notes: "Debug only.",
  },
  {
    id: "debug_control_search_top3_battle",
    name: "Debug 戦探し",
    card_type: "control",
    rarity: "rare",
    attack: 0,
    block: 0,
    speed: 0,
    tags: ["debug", "search"],
    effect_text: "自分の山札の上から3枚を見て、battleカードを1枚手札に加える。",
    enabled: true,
    play_zone: "instant",
    after_play_zone: "discard",
    slot_type: "",
    flavor_text: "",
    effects: [
      {
        id: "debug_control_search_top3_battle_01",
        seq: 1,
        enabled: true,
        trigger: "on_play",
        priority: 100,
        effect_type: "custom",
        keyword: "debug_search_top3_battle",
        display_text: "自分の山札の上から3枚を見て、battleカードを1枚手札に加える。",
      },
    ],
    notes: "Debug only.",
  },
  {
    id: "debug_control_recover_discard_battle",
    name: "Debug 戦回収",
    card_type: "control",
    rarity: "rare",
    attack: 0,
    block: 0,
    speed: 0,
    tags: ["debug", "recover"],
    effect_text: "自分の捨て札からbattleカードを1枚手札に加える。",
    enabled: true,
    play_zone: "instant",
    after_play_zone: "discard",
    slot_type: "",
    flavor_text: "",
    effects: [
      {
        id: "debug_control_recover_discard_battle_01",
        seq: 1,
        enabled: true,
        trigger: "on_play",
        priority: 100,
        effect_type: "custom",
        keyword: "debug_recover_discard_battle",
        display_text: "自分の捨て札からbattleカードを1枚手札に加える。",
      },
    ],
    notes: "Debug only.",
  },
];
